# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from typing import List
import os


class DropLabel(QtWidgets.QLabel):
    def __init__(self, parent_widget, parent_obj):
        QtWidgets.QLabel.__init__(self, parent_widget)
        self.setAcceptDrops(True)
        self.original_stylesheet = """QLabel{\
                        border: 2px dashed grey;\
                        border-radius: 5px;\
                        font-weight: bold;
        }"""
        self.parent_ = parent_obj

    def dragEnterEvent(self, event: QtGui.QDropEvent):
        if event.mimeData().hasText():
            self.setStyleSheet("""QLabel{
            border: 2px dashed black;\
            border-radius: 5px;\
            color:  rgb(85, 87, 83);\
            font: 75 25pt "Yrsa";\
            font-weight: bold;\
            background-color: rgb(186, 189, 182);\
            padding: 0px;}""")
            event.acceptProposedAction()

    def dropEvent(self, event: QtGui.QDropEvent):
        print("Am here")
        if event.mimeData().hasText():  # it'll be valid for only text drag and drop
            dropped_text: str = event.mimeData().text()
            print(dropped_text)
        self.setStyleSheet(self.original_stylesheet)
        event.acceptProposedAction()
        self.update()


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_left_details = QtWidgets.QFrame(self.centralwidget)
        self.frame_left_details.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_details.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_details.setObjectName("frame_left_details")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_left_details)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_drop_section = QtWidgets.QFrame(self.frame_left_details)
        self.frame_drop_section.setMinimumSize(QtCore.QSize(400, 0))
        self.frame_drop_section.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_drop_section.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_drop_section.setObjectName("frame_drop_section")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_drop_section)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.frame_drop_section)
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 1, 0, 1, 1)
        self.label_drop = DropLabel(self.frame_drop_section, self)
        self.label_drop.setMinimumSize(QtCore.QSize(100, 100))
        self.label_drop.setMaximumSize(QtCore.QSize(16777215, 120))
        self.label_drop.setAcceptDrops(True)
        self.label_drop.setStyleSheet("QLabel{\n"
                                      "    border: 2px dashed grey;\n"
                                      "    border-radius: 5px;\n"
                                      "}")
        self.label_drop.setAlignment(QtCore.Qt.AlignCenter)
        self.label_drop.setObjectName("label_drop")
        self.gridLayout_3.addWidget(self.label_drop, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_drop_section, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_left_details, 0, 0, 1, 1)
        self.frame_graph_right = QtWidgets.QFrame(self.centralwidget)
        self.frame_graph_right.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_graph_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_graph_right.setObjectName("frame_graph_right")
        self.gridLayout_2.addWidget(self.frame_graph_right, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "You can drag & drop the selected text below:"))
        self.label_drop.setText(_translate("MainWindow", "Drop here"))
